server:
  port: 9001
spring:
  application:
    name: consumer-books
  jackson:
    default-property-inclusion: non_null   #如果返回的对象为空则不展示
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss:S
eureka:
  client:
    register-with-eureka: false #不将自己注册到eureka
    service-url:
      defaultZone: http://eureka8760.com:8760/eureka/,http://eureka8761.com:8761/eureka/,http://eureka8762.com:8762/eureka/
  instance:
    instance-id: consumer-books9001
    prefer-ip-address: true