server:
  port: 8762
eureka:
  instance:
    hostname: eureka8762.com
  client:
    register-with-eureka: false #不将自己注册到eureka
    fetch-registry: false #不从eureka上获取服务的注册信息
    service-url:
      defaultZone: http://eureka8760.com:8760/eureka/,http://eureka8761.com:8761/eureka/
  server:
    enable-self-preservation: true #开启自我保护机制